# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 421)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("* {\n"
"background: white;\n"
"color: black;\n"
"border: none;\n"
"    font: 11pt \"Manrope\";\n"
"}\n"
"\n"
"QLineEdit {\n"
"padding: 5px;\n"
"border: 1px solid lightgrey;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"/* QPushButton styling */\n"
"QPushButton {\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"    padding: 5px 15px;\n"
"    font-size: 14px;\n"
"    background-color: #e7e7e7;\n"
"    color: #333;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d4d4d4;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b5b5b5;\n"
"}\n"
"\n"
"QPushButton[style=\"accent\"] {\n"
"    background-color: #4CAF50;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"/* QCheckBox styles */\n"
"QCheckBox::indicator:unchecked {\n"
"    border: 1px solid #aaa;\n"
"    background: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(checked_icon_path.png);\n"
"}\n"
"\n"
"/* QRadioButton styles */\n"
"QRadioButton::indicator:unchecked {\n"
"    border: 1px solid #aaa;\n"
"    background: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    image: url(radio_checked_icon_path.png);\n"
"}\n"
"\n"
"/* QTabWidget styles */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabWidget QTabButton {\n"
"    padding: 5px;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"    background: #f5f5f5;\n"
"}\n"
"\n"
"QTabWidget QTabButton:selected {\n"
"    background: #e7e7e7;\n"
"}\n"
"\n"
"/* QComboBox */\n"
"QComboBox {\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    background: #f5f5f5;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(dropdown_arrow_icon_path.png);\n"
"}\n"
"\n"
"\n"
"#submitBtn {\n"
"background-color: #22733F;\n"
"color: white;\n"
"}\n"
"\n"
"#logoBtn {\n"
"background: none;\n"
"border: none;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.footerLabel = QtWidgets.QLabel(self.centralwidget)
        self.footerLabel.setStyleSheet("padding-left: 10px;\n"
"background: #F2F2F2")
        self.footerLabel.setObjectName("footerLabel")
        self.gridLayout.addWidget(self.footerLabel, 4, 0, 1, 2)
        self.headerLabel = QtWidgets.QLabel(self.centralwidget)
        self.headerLabel.setStyleSheet("font: 125 18pt \"Montserrat\";\n"
"font: 81 16pt \"Montserrat\";\n"
"padding: 10px;\n"
"background: rgb(255, 131, 30)")
        self.headerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.gridLayout.addWidget(self.headerLabel, 0, 0, 1, 2)
        self.logoBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoBtn.sizePolicy().hasHeightForWidth())
        self.logoBtn.setSizePolicy(sizePolicy)
        self.logoBtn.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.logoBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoBtn.setIcon(icon)
        self.logoBtn.setIconSize(QtCore.QSize(200, 300))
        self.logoBtn.setObjectName("logoBtn")
        self.gridLayout.addWidget(self.logoBtn, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font-size: 18pt")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.submitBtn = QtWidgets.QPushButton(self.frame)
        self.submitBtn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.submitBtn.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background-color: rgb(97, 255, 155);\n"
"background-color: rgb(255, 119, 56)\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(255, 99, 26);\n"
"}\n"
"\n"
"QPushButton::clicked {\n"
"\n"
"background-color: rgb(255, 99, 26);\n"
"}")
        self.submitBtn.setObjectName("submitBtn")
        self.verticalLayout.addWidget(self.submitBtn, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.gridLayout.addWidget(self.frame, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.footerLabel.setText(_translate("MainWindow", "Copyright (C) 2023"))
        self.headerLabel.setText(_translate("MainWindow", "Welcome to My APP"))
        self.label.setText(_translate("MainWindow", "License Key"))
        self.submitBtn.setText(_translate("MainWindow", "Submit"))

